import { TenantContextService } from './shared/tenant/tenant-context.service';
import { AiCircuitBreakerEngine } from './ai/engine/ai-circuit-breaker.engine';
import { ReadReplicaRouterService } from './shared/database/read-replica-router.service';

async function main() {
  console.log('========================================================================');
  console.log('🚀 TESTING 2026 SOTA ENTERPRISE SAAS ARCHITECTURAL PATTERNS FOR LEGALOS');
  console.log('========================================================================\n');

  // -------------------------------------------------------------------
  // 1. TEST PATTERN 1: TRANSACTION-SCOPED RLS TENANT CONTEXT
  // -------------------------------------------------------------------
  console.log('[PATTERN 1] Testing Transaction-Scoped Tenant Context & SET Query Generator...');
  const tenantContextService = new TenantContextService();
  const sampleTenantId = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';

  const rlsQuery = tenantContextService.generateRlsTransactionQuery(sampleTenantId);
  console.log(`- Generated RLS Transaction Query: "${rlsQuery}"`);

  if (!rlsQuery.includes("set_config('app.current_tenant_id'") || !rlsQuery.includes(', true);')) {
    throw new Error('Transaction-scoped RLS query generation failed!');
  }

  await TenantContextService.run(
    { tenantId: sampleTenantId, traceId: 'trace-otel-2026-991', userRole: 'Partner' },
    async () => {
      const activeTenant = TenantContextService.getTenantId();
      const session = TenantContextService.getSession();
      console.log(`- OpenTelemetry Scoped Session: TenantId=${activeTenant}, TraceId=${session?.traceId}`);

      if (activeTenant !== sampleTenantId || session?.traceId !== 'trace-otel-2026-991') {
        throw new Error('Tenant context propagation failed!');
      }
    },
  );
  console.log('✔ Pattern 1 (Transaction-Scoped RLS Context) PASSED 100%!\n');

  // -------------------------------------------------------------------
  // 2. TEST PATTERN 2: AI CIRCUIT BREAKER & SAUDI LOCAL LLM FAILOVER
  // -------------------------------------------------------------------
  console.log('[PATTERN 2] Testing AI Circuit Breaker Engine & Emergency Failover...');
  const circuitEngine = new AiCircuitBreakerEngine();

  // Test 1: Successful Primary Provider Call
  const normalCall = await circuitEngine.executeWithCircuitBreaker('CLAUDE_3_5', async (provider) => {
    return `Response generated by ${provider}`;
  });
  console.log(`- Normal Call Provider: ${normalCall.activeProvider} (FailedOver: ${normalCall.failedOver})`);

  // Test 2: Simulating Failure of Cloud AI Provider -> Failover to Saudi Local LLM
  const failedOverCall = await circuitEngine.executeWithCircuitBreaker('CLAUDE_3_5', async (provider) => {
    if (provider === 'CLAUDE_3_5') {
      throw new Error('Cloud Provider API 503 Gateway Timeout');
    }
    return `Emergency Response generated by ${provider}`;
  });
  console.log(`- Failed-Over Provider: ${failedOverCall.activeProvider} (FailedOver: ${failedOverCall.failedOver})`);

  if (failedOverCall.activeProvider !== 'SAUDI_LOCAL_LLM' || !failedOverCall.failedOver) {
    throw new Error('AI Circuit Breaker Failover failed!');
  }
  console.log('✔ Pattern 2 (AI Circuit Breaker & Saudi Local LLM Failover) PASSED 100%!\n');

  // -------------------------------------------------------------------
  // 3. TEST PATTERN 3: READ REPLICA QUERY ROUTING ENGINE
  // -------------------------------------------------------------------
  console.log('[PATTERN 3] Testing Read Replica Query Router for Analytics & Reports...');
  const prismaMock: any = {};
  const replicaRouter = new ReadReplicaRouterService(prismaMock);

  const writeTarget = replicaRouter.resolveDatabaseNode('WRITE');
  console.log(`- Write Target Node: [${writeTarget.nodeId}] (Role: ${writeTarget.role})`);

  const readTarget = replicaRouter.resolveDatabaseNode('READ_ANALYTICS');
  console.log(`- Read Analytics Target Node: [${readTarget.nodeId}] (Role: ${readTarget.role}, Latency: ${readTarget.latencyMs}ms)`);

  if (writeTarget.role !== 'PRIMARY' || readTarget.role !== 'READ_REPLICA') {
    throw new Error('Read Replica Query Routing failed!');
  }
  console.log('✔ Pattern 3 (Read Replica Query Routing) PASSED 100%!\n');

  console.log('========================================================================');
  console.log('🎉 ALL 2026 SOTA ARCHITECTURAL PATTERNS PASSED VERIFICATION 100%!');
  console.log('========================================================================');
}

main().catch((err) => {
  console.error('SOTA Architecture Verification Failed:', err);
  process.exit(1);
});
